import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  t: (key: string) => string;
  setLanguage: (lang: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const enTranslations = {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    budgets: 'Budgets',
    wallets: 'Wallets',
    gam3eya: 'Gam3eya',
    reminders: 'Reminders',
    reports: 'Reports',
    settings: 'Settings',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    create_account: 'Create Account',
    already_have_account: 'Already have an account?',
    login_here: 'Login here',
    need_an_account: 'Need an account?',
    register_here: 'Register here',
    enter_username: 'Enter your username',
    enter_email: 'Enter your email',
    enter_password: 'Enter your password',
    enter_confirm_password: 'Enter your confirm password',
    invalid_email: 'Invalid email',
    passwords_do_not_match: 'Passwords do not match',
    home: 'Home',
    total_balance: 'Total Balance',
    income: 'Income',
    expenses: 'Expenses',
    latest_transactions: 'Latest Transactions',
    view_all: 'View All',
    add_transaction: 'Add Transaction',
    date: 'Date',
    amount: 'Amount',
    description: 'Description',
    category: 'Category',
    wallet: 'Wallet',
    type: 'Type',
    income_transaction: 'Income Transaction',
    expense_transaction: 'Expense Transaction',
    select_category: 'Select Category',
    select_wallet: 'Select Wallet',
    enter_amount: 'Enter amount',
    enter_description: 'Enter description',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    are_you_sure: 'Are you sure?',
    this_action_cannot_be_undone: 'This action cannot be undone.',
    yes_delete: 'Yes, Delete',
    no_cancel: 'No, Cancel',
    new_wallet: 'New Wallet',
    name: 'Name',
    balance: 'Balance',
    color: 'Color',
    type_of_wallet: 'Type of Wallet',
    enter_name: 'Enter name',
    enter_balance: 'Enter balance',
    select_color: 'Select color',
    create: 'Create',
    edit_wallet: 'Edit Wallet',
    cash: 'Cash',
    bank_account: 'Bank Account',
    credit_card: 'Credit Card',
    debit_card: 'Debit Card',
    mobile_money: 'Mobile Money',
    investment: 'Investment',
    other: 'Other',
    total: 'Total',
    remaining: 'Remaining',
    spent: 'Spent',
    budget_amount: 'Budget Amount',
    start_date: 'Start Date',
    end_date: 'End Date',
    create_budget: 'Create Budget',
    edit_budget: 'Edit Budget',
    enter_budget_amount: 'Enter budget amount',
    select_start_date: 'Select start date',
    select_end_date: 'Select end date',
    new_category: 'New Category',
    category_name: 'Category Name',
    category_type: 'Category Type',
    enter_category_name: 'Enter category name',
    select_category_type: 'Select category type',
    expense: 'Expense',
    income_category: 'Income',
    both: 'Both',
    is_custom: 'Is Custom',
    category_added_successfully: 'Category added successfully!',
    failed_to_add_category: 'Failed to add category.',
    category_already_exists: 'Category with the same name already exists for this type.',
    info: 'Info',
    categories_reset_not_available: 'Categories reset functionality is not available yet.',
    error: 'Error',
    failed_to_load_categories: 'Failed to load categories.',
    success: 'Success',
    logged_in_successfully: 'Logged in successfully!',
    registered_successfully: 'Registered successfully!',
    logged_out_successfully: 'Logged out successfully!',
    invalid_credentials: 'Invalid credentials',
    monthly: "Monthly",
    yearly: "Yearly",
    monthly_comparison: "Monthly income vs expenses",
    yearly_comparison: "Yearly income vs expenses",
    monthly_cash_flow: "Monthly cash flow analysis",
    yearly_cash_flow: "Yearly cash flow analysis",
    cash_flow: "Cash Flow",
    balance: "Balance",
    monthly_distribution: "Monthly expense distribution",
    yearly_distribution: "Yearly expense distribution",
    income_expense_comparison_description: "Compare your income and expenses over time",
    cash_flow_description: "Track your net cash flow and running balance",
    expense_distribution_description: "See where your money is going",
    wallet_transaction_history: "Recent transaction history",
    uncategorized: "Uncategorized",
  };

  const arTranslations = {
    dashboard: 'لوحة التحكم',
    transactions: 'المعاملات',
    budgets: 'الميزانيات',
    wallets: 'المحافظ',
    gam3eya: 'جمعية',
    reminders: 'تذكيرات',
    reports: 'تقارير',
    settings: 'إعدادات',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirm_password: 'تأكيد كلمة المرور',
    create_account: 'إنشاء حساب',
    already_have_account: 'هل لديك حساب بالفعل؟',
    login_here: 'تسجيل الدخول هنا',
    need_an_account: 'تحتاج إلى حساب؟',
    register_here: 'سجل هنا',
    enter_username: 'أدخل اسم المستخدم الخاص بك',
    enter_email: 'أدخل بريدك الإلكتروني',
    enter_password: 'أدخل كلمة المرور الخاصة بك',
    enter_confirm_password: 'أدخل تأكيد كلمة المرور',
    invalid_email: 'بريد إلكتروني خاطئ',
    passwords_do_not_match: 'كلمات المرور غير متطابقة',
    home: 'الرئيسية',
    total_balance: 'الرصيد الإجمالي',
    income: 'الدخل',
    expenses: 'المصروفات',
    latest_transactions: 'أحدث المعاملات',
    view_all: 'عرض الكل',
    add_transaction: 'إضافة معاملة',
    date: 'التاريخ',
    amount: 'المبلغ',
    description: 'الوصف',
    category: 'الفئة',
    wallet: 'المحفظة',
    type: 'النوع',
    income_transaction: 'معاملة دخل',
    expense_transaction: 'معاملة مصروف',
    select_category: 'اختر فئة',
    select_wallet: 'اختر محفظة',
    enter_amount: 'أدخل المبلغ',
    enter_description: 'أدخل الوصف',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    are_you_sure: 'هل أنت متأكد؟',
    this_action_cannot_be_undone: 'لا يمكن التراجع عن هذا الإجراء.',
    yes_delete: 'نعم، احذف',
    no_cancel: 'لا، إلغاء',
    new_wallet: 'محفظة جديدة',
    name: 'الاسم',
    balance: 'الرصيد',
    color: 'اللون',
    type_of_wallet: 'نوع المحفظة',
    enter_name: 'أدخل الاسم',
    enter_balance: 'أدخل الرصيد',
    select_color: 'اختر اللون',
    create: 'إنشاء',
    edit_wallet: 'تعديل المحفظة',
    cash: 'نقدي',
    bank_account: 'حساب بنكي',
    credit_card: 'بطاقة ائتمان',
    debit_card: 'بطاقة خصم',
    mobile_money: 'المال عبر الهاتف المحمول',
    investment: 'استثمار',
    other: 'أخرى',
    total: 'المجموع',
    remaining: 'المتبقي',
    spent: 'صرف',
    budget_amount: 'مبلغ الميزانية',
    start_date: 'تاريخ البدء',
    end_date: 'تاريخ الانتهاء',
    create_budget: 'إنشاء ميزانية',
    edit_budget: 'تعديل الميزانية',
    enter_budget_amount: 'أدخل مبلغ الميزانية',
    select_start_date: 'اختر تاريخ البدء',
    select_end_date: 'اختر تاريخ الانتهاء',
    new_category: 'فئة جديدة',
    category_name: 'اسم الفئة',
    category_type: 'نوع الفئة',
    enter_category_name: 'أدخل اسم الفئة',
    select_category_type: 'اختر نوع الفئة',
    expense: 'مصروف',
    income_category: 'دخل',
    both: 'كلاهما',
    is_custom: 'مخصص',
    category_added_successfully: 'تمت إضافة الفئة بنجاح!',
    failed_to_add_category: 'فشل في إضافة الفئة.',
    category_already_exists: 'فئة بنفس الاسم موجودة بالفعل لهذا النوع.',
    info: 'معلومات',
    categories_reset_not_available: 'وظيفة إعادة تعيين الفئات غير متاحة بعد.',
    error: 'خطأ',
    failed_to_load_categories: 'فشل في تحميل الفئات.',
    success: 'نجاح',
    logged_in_successfully: 'تم تسجيل الدخول بنجاح!',
    registered_successfully: 'تم التسجيل بنجاح!',
    logged_out_successfully: 'تم تسجيل الخروج بنجاح!',
    invalid_credentials: 'بيانات اعتماد غير صالحة',
    monthly: "شهري",
    yearly: "سنوي",
    monthly_comparison: "الدخل مقابل المصروفات الشهرية",
    yearly_comparison: "الدخل مقابل المصروفات السنوية",
    monthly_cash_flow: "تحليل التدفق النقدي الشهري",
    yearly_cash_flow: "تحليل التدفق النقدي السنوي",
    cash_flow: "التدفق النقدي",
    balance: "الرصيد",
    monthly_distribution: "توزيع المصروفات الشهرية",
    yearly_distribution: "توزيع المصروفات السنوية",
    income_expense_comparison_description: "قارن دخلك ومصروفاتك على مر الزمن",
    cash_flow_description: "تتبع صافي التدفق النقدي والرصيد الجاري",
    expense_distribution_description: "معرفة أين تذهب أموالك",
    wallet_transaction_history: "سجل المعاملات الأخيرة",
    uncategorized: "غير مصنف",
  };

  const translations = language === 'ar' ? arTranslations : enTranslations;

  const t = (key: string) => {
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

