import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  t: (key: string) => string;
  setLanguage: (lang: string) => void;
  toggleLanguage: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState(localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const enTranslations = {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    budgets: 'Budgets',
    wallets: 'Wallets',
    gam3eya: 'Gam3eya',
    reminders: 'Reminders',
    reports: 'Reports',
    settings: 'Settings',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    create_account: 'Create Account',
    already_have_account: 'Already have an account?',
    login_here: 'Login here',
    need_an_account: 'Need an account?',
    register_here: 'Register here',
    enter_username: 'Enter your username',
    enter_email: 'Enter your email',
    enter_password: 'Enter your password',
    enter_confirm_password: 'Enter your confirm password',
    invalid_email: 'Invalid email',
    passwords_do_not_match: 'Passwords do not match',
    home: 'Home',
    total_balance: 'Total Balance',
    income: 'Income',
    expenses: 'Expenses',
    latest_transactions: 'Latest Transactions',
    view_all: 'View All',
    add_transaction: 'Add Transaction',
    date: 'Date',
    amount: 'Amount',
    description: 'Description',
    category: 'Category',
    wallet: 'Wallet',
    type: 'Type',
    income_transaction: 'Income Transaction',
    expense_transaction: 'Expense Transaction',
    select_category: 'Select Category',
    select_wallet: 'Select Wallet',
    enter_amount: 'Enter amount',
    enter_description: 'Enter description',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    are_you_sure: 'Are you sure?',
    this_action_cannot_be_undone: 'This action cannot be undone.',
    yes_delete: 'Yes, Delete',
    no_cancel: 'No, Cancel',
    new_wallet: 'New Wallet',
    name: 'Name',
    balance: 'Balance',
    color: 'Color',
    type_of_wallet: 'Type of Wallet',
    enter_name: 'Enter name',
    enter_balance: 'Enter balance',
    select_color: 'Select color',
    create: 'Create',
    edit_wallet: 'Edit Wallet',
    cash: 'Cash',
    bank_account: 'Bank Account',
    credit_card: 'Credit Card',
    debit_card: 'Debit Card',
    mobile_money: 'Mobile Money',
    investment: 'Investment',
    other: 'Other',
    total: 'Total',
    remaining: 'Remaining',
    spent: 'Spent',
    budget_amount: 'Budget Amount',
    start_date: 'Start Date',
    end_date: 'End Date',
    create_budget: 'Create Budget',
    edit_budget: 'Edit Budget',
    enter_budget_amount: 'Enter budget amount',
    select_start_date: 'Select start date',
    select_end_date: 'Select end date',
    new_category: 'New Category',
    category_name: 'Category Name',
    category_type: 'Category Type',
    enter_category_name: 'Enter category name',
    select_category_type: 'Select category type',
    expense: 'Expense',
    income_category: 'Income',
    both: 'Both',
    is_custom: 'Is Custom',
    category_added_successfully: 'Category added successfully!',
    failed_to_add_category: 'Failed to add category.',
    category_already_exists: 'Category with the same name already exists for this type.',
    info: 'Info',
    categories_reset_not_available: 'Categories reset functionality is not available yet.',
    error: 'Error',
    failed_to_load_categories: 'Failed to load categories.',
    success: 'Success',
    logged_in_successfully: 'Logged in successfully!',
    registered_successfully: 'Registered successfully!',
    logged_out_successfully: 'Logged out successfully!',
    invalid_credentials: 'Invalid credentials',
    monthly: "Monthly",
    yearly: "Yearly",
    monthly_comparison: "Monthly income vs expenses",
    yearly_comparison: "Yearly income vs expenses",    monthly_cash_flow: "Monthly cash flow analysis",
    yearly_cash_flow: "Yearly cash flow analysis",
    cash_flow: "Cash Flow",
    monthly_distribution: "Monthly expense distribution",
    yearly_distribution: "Yearly expense distribution",
    income_expense_comparison_description: "Compare your income and expenses over time",
    cash_flow_description: "Track your net cash flow and running balance",
    expense_distribution_description: "See where your money is going",    wallet_transaction_history: "Recent transaction history",
    uncategorized: "Uncategorized",
    
    // Missing filter/search translations
    search_transactions: 'Search transactions',
    filter: 'Filter',
    clear_filters: 'Clear filters',
    sort: 'Sort',
    date_from: 'Date from',
    date_to: 'Date to',
    categories: 'Categories',
    types: 'Types',
    search: 'Search',
    max: 'Max',
    
    // Missing settings translations
    language_settings: 'Language Settings',
    current_language: 'Current language',
    notifications: 'Notifications',
    manage_notifications: 'Manage your notification preferences',
    
    // Missing wallet translations
    add_wallet: 'Add Wallet',
    
    // Missing general UI translations
    no_results_found: 'No results found',
    loading: 'Loading...',
    save: 'Save',
    close: 'Close',
      // Language toggle translations
    arabic: 'العربية',
    english: 'English',
      // Sorting related translations
    sort_by: 'Sort by',
    order: 'Order',
    select_sort_key: 'Select sort key',
    select_sort_direction: 'Select sort direction',
    ascending: 'Ascending',
    descending: 'Descending',
    
    // Missing Settings translations
    phone: 'Phone',
    profile_settings: 'Profile Settings',
    switch_to_arabic: 'Switch to Arabic',
    switch_to_english: 'Switch to English',
    email_notifications: 'Email notifications',
    receive_email_updates: 'Receive email updates about your account',
    push_notifications: 'Push notifications',
    receive_push_notifications: 'Receive push notifications on your device',
    security: 'Security',
    change_password: 'Change Password',    manage_connected_accounts: 'Manage Connected Accounts',
    edit_profile: 'Edit Profile',
    save_changes: 'Save Changes',
    
    // Missing Wallet translations
    my_wallets: 'My Wallets',
    manage_your_wallets: 'Manage your wallets and track balances',
    no_wallets_yet: 'No wallets yet',
    add_new_wallet: 'Add New Wallet',
    enter_wallet_details: 'Enter details for your new wallet',
    wallet_name: 'Wallet Name',
    wallet_type: 'Wallet Type',
    select_wallet_type: 'Select wallet type',
    initial_balance: 'Initial Balance',
    wallet_color: 'Wallet Color',
    account_number: 'Account Number',
    last_updated: 'Last Updated',
    no_wallets: 'No wallets available',
    wallet_added_successfully: 'Wallet added successfully',
    failed_to_add_wallet: 'Failed to add wallet',
    wallet_deleted_successfully: 'Wallet deleted successfully',
    failed_to_delete_wallet: 'Failed to delete wallet',
    validation_error: 'Validation Error',
    please_fill_all_required_fields: 'Please fill all required fields',
    failed_to_load_wallets: 'Failed to load wallets',
    
    // Wallet types
    bank: 'Bank',
    savings: 'Savings',
    custom: 'Custom',
    
    // Missing payment/transaction related
    current_balance: 'Current Balance',
    make_monthly_contribution: 'Make Monthly Contribution',
    receive_gam3eya_payout: 'Receive Gam3eya Payout',
    select_wallet_to_pay_from: 'Select wallet to pay from',
    select_wallet_to_receive_into: 'Select wallet to receive into',
    no_wallets_with_sufficient_balance: 'No wallets with sufficient balance',
    no_wallets_available: 'No wallets available',
    processing: 'Processing...',
    confirm: 'Confirm',
    monthly_contribution_for_cycle: 'Monthly contribution for cycle {{cycle}}',
    receiving_payout_for_gam3eya: 'Receiving payout for gam3eya',
    after_payment_wallet_balance_will_be: 'After payment, wallet balance will be {{balance}}',
    after_payout_wallet_balance_will_be: 'After payout, wallet balance will be {{balance}}',
    payment_processed_successfully: 'Payment processed successfully',
    payout_processed_successfully: 'Payout processed successfully',
    payment_processing_failed: 'Payment processing failed',
    please_select_wallet: 'Please select a wallet',
    pay: 'Pay',
    receive: 'Receive',
    next_payment: 'Next payment',    last_processed: 'Last processed',
    
    // Loading states
    loading_wallets: 'Loading wallets',
  };

  const arTranslations = {
    dashboard: 'لوحة التحكم',
    transactions: 'المعاملات',
    budgets: 'الميزانيات',
    wallets: 'المحافظ',
    gam3eya: 'جمعية',
    reminders: 'تذكيرات',
    reports: 'تقارير',
    settings: 'إعدادات',
    login: 'تسجيل الدخول',
    register: 'تسجيل',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirm_password: 'تأكيد كلمة المرور',
    create_account: 'إنشاء حساب',
    already_have_account: 'هل لديك حساب بالفعل؟',
    login_here: 'تسجيل الدخول هنا',
    need_an_account: 'تحتاج إلى حساب؟',
    register_here: 'سجل هنا',
    enter_username: 'أدخل اسم المستخدم الخاص بك',
    enter_email: 'أدخل بريدك الإلكتروني',
    enter_password: 'أدخل كلمة المرور الخاصة بك',
    enter_confirm_password: 'أدخل تأكيد كلمة المرور',
    invalid_email: 'بريد إلكتروني خاطئ',
    passwords_do_not_match: 'كلمات المرور غير متطابقة',
    home: 'الرئيسية',
    total_balance: 'الرصيد الإجمالي',
    income: 'الدخل',
    expenses: 'المصروفات',
    latest_transactions: 'أحدث المعاملات',
    view_all: 'عرض الكل',
    add_transaction: 'إضافة معاملة',
    date: 'التاريخ',
    amount: 'المبلغ',
    description: 'الوصف',
    category: 'الفئة',
    wallet: 'المحفظة',
    type: 'النوع',
    income_transaction: 'معاملة دخل',
    expense_transaction: 'معاملة مصروف',
    select_category: 'اختر فئة',
    select_wallet: 'اختر محفظة',
    enter_amount: 'أدخل المبلغ',
    enter_description: 'أدخل الوصف',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    are_you_sure: 'هل أنت متأكد؟',
    this_action_cannot_be_undone: 'لا يمكن التراجع عن هذا الإجراء.',
    yes_delete: 'نعم، احذف',
    no_cancel: 'لا، إلغاء',
    new_wallet: 'محفظة جديدة',
    name: 'الاسم',
    balance: 'الرصيد',
    color: 'اللون',
    type_of_wallet: 'نوع المحفظة',
    enter_name: 'أدخل الاسم',
    enter_balance: 'أدخل الرصيد',
    select_color: 'اختر اللون',
    create: 'إنشاء',
    edit_wallet: 'تعديل المحفظة',
    cash: 'نقدي',
    bank_account: 'حساب بنكي',
    credit_card: 'بطاقة ائتمان',
    debit_card: 'بطاقة خصم',
    mobile_money: 'المال عبر الهاتف المحمول',
    investment: 'استثمار',
    other: 'أخرى',
    total: 'المجموع',
    remaining: 'المتبقي',
    spent: 'صرف',
    budget_amount: 'مبلغ الميزانية',
    start_date: 'تاريخ البدء',
    end_date: 'تاريخ الانتهاء',
    create_budget: 'إنشاء ميزانية',
    edit_budget: 'تعديل الميزانية',
    enter_budget_amount: 'أدخل مبلغ الميزانية',
    select_start_date: 'اختر تاريخ البدء',
    select_end_date: 'اختر تاريخ الانتهاء',
    new_category: 'فئة جديدة',
    category_name: 'اسم الفئة',
    category_type: 'نوع الفئة',
    enter_category_name: 'أدخل اسم الفئة',
    select_category_type: 'اختر نوع الفئة',
    expense: 'مصروف',
    income_category: 'دخل',
    both: 'كلاهما',
    is_custom: 'مخصص',
    category_added_successfully: 'تمت إضافة الفئة بنجاح!',
    failed_to_add_category: 'فشل في إضافة الفئة.',
    category_already_exists: 'فئة بنفس الاسم موجودة بالفعل لهذا النوع.',
    info: 'معلومات',
    categories_reset_not_available: 'وظيفة إعادة تعيين الفئات غير متاحة بعد.',
    error: 'خطأ',
    failed_to_load_categories: 'فشل في تحميل الفئات.',
    success: 'نجاح',
    logged_in_successfully: 'تم تسجيل الدخول بنجاح!',
    registered_successfully: 'تم التسجيل بنجاح!',
    logged_out_successfully: 'تم تسجيل الخروج بنجاح!',
    invalid_credentials: 'بيانات اعتماد غير صالحة',
    monthly: "شهري",
    yearly: "سنوي",
    monthly_comparison: "الدخل مقابل المصروفات الشهرية",
    yearly_comparison: "الدخل مقابل المصروفات السنوية",    monthly_cash_flow: "تحليل التدفق النقدي الشهري",
    yearly_cash_flow: "تحليل التدفق النقدي السنوي",
    cash_flow: "التدفق النقدي",
    monthly_distribution: "توزيع المصروفات الشهرية",
    yearly_distribution: "توزيع المصروفات السنوية",
    income_expense_comparison_description: "قارن دخلك ومصروفاتك على مر الزمن",
    cash_flow_description: "تتبع صافي التدفق النقدي والرصيد الجاري",
    expense_distribution_description: "معرفة أين تذهب أموالك",    wallet_transaction_history: "سجل المعاملات الأخيرة",
    uncategorized: "غير مصنف",
    
    // Arabic filter/search translations
    search_transactions: 'البحث في المعاملات',
    filter: 'تصفية',
    clear_filters: 'مسح المرشحات',
    sort: 'ترتيب',
    date_from: 'من تاريخ',
    date_to: 'إلى تاريخ',
    categories: 'الفئات',
    types: 'الأنواع',
    search: 'بحث',
    max: 'الحد الأقصى',
    
    // Arabic settings translations
    language_settings: 'إعدادات اللغة',
    current_language: 'اللغة الحالية',
    notifications: 'الإشعارات',
    manage_notifications: 'إدارة تفضيلات الإشعارات',
    
    // Arabic wallet translations
    add_wallet: 'إضافة محفظة',
    
    // Arabic general UI translations
    no_results_found: 'لا توجد نتائج',
    loading: 'جاري التحميل...',
    save: 'حفظ',
    close: 'إغلاق',
      // Language toggle translations
    arabic: 'العربية',
    english: 'English',
      // Arabic sorting related translations
    sort_by: 'ترتيب حسب',
    order: 'الترتيب',
    select_sort_key: 'اختر مفتاح الترتيب',
    select_sort_direction: 'اختر اتجاه الترتيب',
    ascending: 'تصاعدي',
    descending: 'تنازلي',
    
    // Missing Arabic Settings translations
    phone: 'الهاتف',
    profile_settings: 'إعدادات الملف الشخصي',
    switch_to_arabic: 'تغيير إلى العربية',
    switch_to_english: 'تغيير إلى الإنجليزية',
    email_notifications: 'إشعارات البريد الإلكتروني',
    receive_email_updates: 'تلقي تحديثات البريد الإلكتروني حول حسابك',
    push_notifications: 'الإشعارات الفورية',
    receive_push_notifications: 'تلقي الإشعارات الفورية على جهازك',
    security: 'الأمان',
    change_password: 'تغيير كلمة المرور',    manage_connected_accounts: 'إدارة الحسابات المتصلة',
    edit_profile: 'تعديل الملف الشخصي',
    save_changes: 'حفظ التغييرات',
    
    // Missing Arabic Wallet translations
    my_wallets: 'محافظي',
    manage_your_wallets: 'إدارة محافظك وتتبع الأرصدة',
    no_wallets_yet: 'لا توجد محافظ بعد',
    add_new_wallet: 'إضافة محفظة جديدة',
    enter_wallet_details: 'أدخل تفاصيل محفظتك الجديدة',
    wallet_name: 'اسم المحفظة',
    wallet_type: 'نوع المحفظة',
    select_wallet_type: 'اختر نوع المحفظة',
    initial_balance: 'الرصيد الأولي',
    wallet_color: 'لون المحفظة',
    account_number: 'رقم الحساب',
    last_updated: 'آخر تحديث',
    no_wallets: 'لا توجد محافظ متاحة',
    wallet_added_successfully: 'تمت إضافة المحفظة بنجاح',
    failed_to_add_wallet: 'فشل في إضافة المحفظة',
    wallet_deleted_successfully: 'تم حذف المحفظة بنجاح',
    failed_to_delete_wallet: 'فشل في حذف المحفظة',
    validation_error: 'خطأ في التحقق',
    please_fill_all_required_fields: 'يرجى ملء جميع الحقول المطلوبة',
    failed_to_load_wallets: 'فشل في تحميل المحافظ',
    
    // Arabic Wallet types
    bank: 'بنك',
    savings: 'مدخرات',
    custom: 'مخصص',
    
    // Missing Arabic payment/transaction related
    current_balance: 'الرصيد الحالي',
    make_monthly_contribution: 'قم بالمساهمة الشهرية',
    receive_gam3eya_payout: 'استلم دفعة الجمعية',
    select_wallet_to_pay_from: 'اختر المحفظة للدفع منها',
    select_wallet_to_receive_into: 'اختر المحفظة لاستلام المبلغ',
    no_wallets_with_sufficient_balance: 'لا توجد محافظ برصيد كافٍ',
    no_wallets_available: 'لا توجد محافظ متاحة',
    processing: 'جاري المعالجة...',
    confirm: 'تأكيد',
    monthly_contribution_for_cycle: 'المساهمة الشهرية للدورة {{cycle}}',
    receiving_payout_for_gam3eya: 'استلام دفعة من الجمعية',
    after_payment_wallet_balance_will_be: 'بعد الدفع، سيكون رصيد المحفظة {{balance}}',
    after_payout_wallet_balance_will_be: 'بعد الاستلام، سيكون رصيد المحفظة {{balance}}',
    payment_processed_successfully: 'تمت معالجة الدفعة بنجاح',
    payout_processed_successfully: 'تمت معالجة الاستلام بنجاح',
    payment_processing_failed: 'فشل في معالجة الدفعة',
    please_select_wallet: 'يرجى اختيار محفظة',
    pay: 'دفع',
    receive: 'استلام',
    next_payment: 'الدفعة التالية',    last_processed: 'آخر معالجة',
    
    // Loading states Arabic
    loading_wallets: 'جاري تحميل المحافظ',
  };

  const translations = language === 'ar' ? arTranslations : enTranslations;
  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'ar' : 'en');
  };

  const t = (key: string) => {
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

